# Generated by Django 3.2.23 on 2024-02-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13),
        ),
    ]
