# Generated by Django 3.2.23 on 2024-02-25 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fhryoutest.in.ua%2Fmodules%2Fbazoviy-modul-4&psig=AOvVaw1gy6zGtSg9BEAMvib_lQBp&ust=1708285501339000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCKDPwsaRs4QDFQAAAAAdAAAAABAJ', null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
